"""sync_database_with_models

Revision ID: 9a36486020a7
Revises: baef0539a3a3
Create Date: 2025-08-24 16:25:03.842210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a36486020a7'
down_revision: Union[str, None] = 'baef0539a3a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'documents', ['document_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'topics', ['topic_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('flashcard_reviews', schema=None) as batch_op:
        batch_op.alter_column('review_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='When the review was submitted',
               existing_nullable=False)
        batch_op.alter_column('review_count',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='Number of times reviewed',
               existing_nullable=False)
        batch_op.drop_constraint('fk_1', type_='foreignkey')
        batch_op.drop_constraint('fk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'flashcards', ['flashcard_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.alter_column('interval',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_constraint('fk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'topics', ['topic_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_constraint('fk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('qa_history', schema=None) as batch_op:
        batch_op.drop_constraint('fk_1', type_='foreignkey')
        batch_op.drop_constraint('fk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'topics', ['topic_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('study_session_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'study_sessions', ['session_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_1', type_='foreignkey')
        batch_op.drop_constraint('fk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'topics', ['topic_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_constraint('fk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_1', 'users', ['owner_id'], ['id'], referent_schema='healthcare_study', ondelete='CASCADE')

    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_2', 'topics', ['topic_id'], ['id'], referent_schema='healthcare_study', ondelete='SET NULL')
        batch_op.create_foreign_key('fk_1', 'users', ['user_id'], ['id'], referent_schema='healthcare_study', ondelete='CASCADE')

    with op.batch_alter_table('study_session_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_1', 'study_sessions', ['session_id'], ['id'], referent_schema='healthcare_study', ondelete='CASCADE')

    with op.batch_alter_table('qa_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_2', 'users', ['user_id'], ['id'], referent_schema='healthcare_study', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_1', 'topics', ['topic_id'], ['id'], referent_schema='healthcare_study', ondelete='CASCADE')

    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_1', 'users', ['user_id'], ['id'], referent_schema='healthcare_study', ondelete='CASCADE')

    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_1', 'topics', ['topic_id'], ['id'], referent_schema='healthcare_study', ondelete='CASCADE')
        batch_op.alter_column('interval',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'1'"),
               existing_nullable=False)

    with op.batch_alter_table('flashcard_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_2', 'users', ['user_id'], ['id'], referent_schema='healthcare_study', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_1', 'flashcards', ['flashcard_id'], ['id'], referent_schema='healthcare_study', ondelete='CASCADE')
        batch_op.alter_column('review_count',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Number of times reviewed',
               existing_nullable=False)
        batch_op.alter_column('review_time',
               existing_type=mysql.DATETIME(),
               comment='When the review was submitted',
               existing_nullable=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_1', 'topics', ['topic_id'], ['id'], referent_schema='healthcare_study', ondelete='CASCADE')

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_1', 'documents', ['document_id'], ['id'], referent_schema='healthcare_study', ondelete='CASCADE')

    # ### end Alembic commands ###
