"""Sync models with database

Revision ID: baef0539a3a3
Revises: 2025_08_22_2230
Create Date: 2025-08-24 14:44:18.722994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'baef0539a3a3'
down_revision: Union[str, None] = '2025_08_22_2230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only include application-specific schema changes
    # System table operations have been removed as they're managed by TiDB
    
    # Add missing index for flashcard reviews
    op.create_index('idx_next_review', 'flashcard_reviews', ['user_id', 'next_review'], unique=False)
    
    # Update server default for flashcards interval
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.alter_column('interval',
                              existing_type=sa.INTEGER(),
                              server_default=sa.text('1'),
                              existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse the application-specific changes
    
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.alter_column('interval',
                              existing_type=sa.INTEGER(),
                              server_default=None,
                              existing_nullable=False)
    
    op.drop_index('idx_next_review', table_name='flashcard_reviews')
    # ### end Alembic commands ###