"""Add StudySession and StudySessionItem models

Revision ID: bfaa6c8f6dc8
Revises: 2025_08_22_1730
Create Date: 2025-08-22 19:18:41.350042

This migration was cleaned to remove system table operations that require elevated permissions.
Only application-specific schema changes should be included.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bfaa6c8f6dc8'
down_revision: Union[str, None] = '2025_08_22_1730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only application-specific schema changes are included
    # System table operations have been removed as they're managed by TiDB
    
    # Create study_sessions table
    op.create_table('study_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('topic_id', sa.Integer(), nullable=True),
        sa.Column('start_time', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('session_type', sa.String(length=50), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create study_session_items table
    op.create_table('study_session_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('content_type', sa.String(length=50), nullable=False),  # 'flashcard', 'document', 'qa', etc.
        sa.Column('content_id', sa.Integer(), nullable=False),
        sa.Column('time_spent', sa.Integer(), nullable=True),  # in seconds
        sa.Column('score', sa.Float(), nullable=True),  # user's self-assessment score
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()),
        sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create index for better query performance
    op.create_index('idx_study_session_user', 'study_sessions', ['user_id'], unique=False)
    op.create_index('idx_study_session_topic', 'study_sessions', ['topic_id'], unique=False)
    op.create_index('idx_study_session_items_session', 'study_session_items', ['session_id'], unique=False)
    op.create_index('idx_study_session_items_content', 'study_session_items', ['content_type', 'content_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_study_session_items_content', table_name='study_session_items')
    op.drop_index('idx_study_session_items_session', table_name='study_session_items')
    op.drop_index('idx_study_session_topic', table_name='study_sessions')
    op.drop_index('idx_study_session_user', table_name='study_sessions')
    op.drop_table('study_session_items')
    op.drop_table('study_sessions')
    # ### end Alembic commands ###
