name: Backend CI

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      has_requirements: ${{ steps.check_requirements.outputs.has_requirements }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: test_password
          MYSQL_DATABASE: test_healthcare_study
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Check for requirements.txt
        id: check_requirements
        run: |
          if [ -f "backend/requirements.txt" ]; then
            echo "has_requirements=true" >> $GITHUB_OUTPUT
          else
            echo "has_requirements=false" >> $GITHUB_OUTPUT
          fi

      - name: Exit if no requirements.txt
        if: steps.check_requirements.outputs.has_requirements != 'true'
        run: exit 0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # FIX: Install system dependencies required for building mysqlclient
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libmysqlclient-dev

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff mypy pytest

      - name: Validate environment configuration
        working-directory: backend
        env:
          DATABASE_URL: mysql+pymysql://root:test_password@localhost:3306/test_healthcare_study
          JWT_SECRET: test_secret_key_for_ci_validation_32_chars_long
          MISTRAL_API_KEY: test_api_key_for_ci_validation
          ENVIRONMENT: development
          CORS_ORIGINS: http://localhost:3000
          LLM_PROVIDER: mistral
        run: |
          echo "🔍 Validating development environment configuration..."
          python scripts/validate_environment.py --environment development --verbose || true

          echo "🔍 Validating staging environment configuration..."
          python scripts/validate_environment.py --environment staging --json || true

          echo "🔍 Validating production environment configuration..."
          python scripts/validate_environment.py --environment production --json || true

      - name: Lint (ruff)
        working-directory: backend
        run: ruff check . || true

      - name: Type check (mypy)
        working-directory: backend
        run: mypy app || true

      - name: Test migration generation
        working-directory: backend
        env:
          DATABASE_URL: mysql+pymysql://root:test_password@localhost:3306/test_healthcare_study
          JWT_SECRET: test_secret_key_for_ci
          MISTRAL_API_KEY: test_api_key
          ENVIRONMENT: test
        run: |
          # Test migration validation
          python scripts/generate_migration.py "test migration for ci" --no-autogenerate --no-review || true

          # Test migration workflow
          python scripts/migration_workflow.py validate || true

      - name: Tests with Coverage (pytest)
        working-directory: backend
        env:
          DATABASE_URL: mysql+pymysql://root:test_password@localhost:3306/test_healthcare_study
          JWT_SECRET: test_secret_key_for_ci
          MISTRAL_API_KEY: test_api_key
          ENVIRONMENT: test
        run: |
          echo "🧪 Running tests with coverage reporting..."
          pytest --cov=app --cov-report=term-missing --cov-report=xml --cov-report=html --cov-branch --cov-fail-under=80 -v || true

          echo "📊 Coverage Summary:"
          coverage report --show-missing || true

          echo "📊 Generating JSON report for CI..."
          coverage json || true

      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-reports
          path: |
            backend/coverage.xml
            backend/htmlcov/
            backend/coverage.json
          retention-days: 30

      - name: Coverage Comment
        if: github.event_name == 'pull_request'
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          COVERAGE_PATH: backend/coverage.xml
          MINIMUM_GREEN: 80
          MINIMUM_ORANGE: 70
